name: CI Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn --batch-mode test verify package --file pom.xml
    - name: Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=garath-github --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar --file pom.xml
